baseURL: https://santanushekhar.com/
languageCode: en-us
title: santanu shekhar
theme : PaperMod

params:

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true

menu : 
  main :
    - identifier : catogories
      name : Categories
      url : /categories/
      weight : 10
    - identifier : tags
      name : Tags
      url : /tags/
      weight : 20
    - identifier : archives
      name : Archives
      url : /archives/
      weight : 30